all: hairdresser client server observer
hairdresser: hairdresser.c
	gcc hairdresser.c -o hairdresser
client: client.c
	gcc client.c -o client
server: server.c 
	gcc server.c -o server
observer: observer.c 
	gcc observer.c -o observer
